const scheduleResolver = window.scheduleEngine.resolveSchedule;
const statusResolver = window.scheduleEngine.resolveItemStatuses;
const config=window.annualWheelConfig;if(!config)throw new Error('Configuration file is missing');
const wheel=document.querySelector('.year-wheel'),stage=document.querySelector('.wheel-stage'),panel=document.querySelector('.schedule-panel'),yearLabel=document.querySelector('#selected-year'),zoomLabel=document.querySelector('#zoom-level');let input,year=config.initialYear==='current'?new Date().getFullYear():config.initialYear,zoom=1,rotation=0,todayAngle=0;const presets=[.88,1,1.16,1.32];
const locale=config.display.locale||'en-GB',date=v=>{const[y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)},copy=d=>new Date(d),fmt=d=>new Intl.DateTimeFormat(locale,{day:'2-digit',month:'short'}).format(d).replace(/\./g,'').toUpperCase(),inputValue=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const nth=(y,m,w,n)=>{const f=new Date(y,m-1,1);return new Date(y,m-1,1+(w-f.getDay()+7)%7+(n-1)*7)},last=(y,m,w)=>{const d=new Date(y,m,0);d.setDate(d.getDate()-(d.getDay()-w+7)%7);return d},next=(d,w)=>{d=copy(d);d.setDate(d.getDate()+((w-d.getDay()+7)%7||7));return d},prev=(d,w)=>{d=copy(d);d.setDate(d.getDate()-((d.getDay()-w+7)%7||7));return d};
const easter=y=>{const a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451);return new Date(y,Math.floor((h+l-7*m+114)/31)-1,(h+l-7*m+114)%31+1)};
const holiday=(d,skip)=>{const y=d.getFullYear(),t=+d;if(skip?.includes('easter')){const e=easter(y),a=copy(e),b=copy(e);a.setDate(e.getDate()-6);b.setDate(e.getDate()+1);if(t>=a&&t<=b)return true}if(skip?.includes('autumn_holiday')){const j=new Date(y,0,4),a=new Date(y,0,4-((j.getDay()||7)-1)+39*7),b=copy(a);b.setDate(a.getDate()+6);if(t>=a&&t<=b)return true}return false};
const course=(start,direction,weekday,count,skip)=>{let d=copy(start),out=[];if(direction==='backward')while(d.getDay()!==weekday)d.setDate(d.getDate()-1);else d=next(new Date(+d-86400000),weekday);while(out.length<count){if(!holiday(d,skip))direction==='backward'?out.unshift(copy(d)):out.push(copy(d));d.setDate(d.getDate()+(direction==='backward'?-7:7))}return out};
const layer=item=>item.layer==='auto'?config.autoLayers[item.kind]:item.layer;
function render(){document.title=config.display.title;document.documentElement.lang=locale;document.querySelector('.brand').lastChild.nodeValue=` ${config.organisation.name}`;document.querySelector('.intro h1').textContent=config.display.title;document.querySelector('.lede').textContent=config.display.description;document.querySelector('.panel-heading .eyebrow').textContent=`${config.organisation.name} · key dates`;document.querySelectorAll('.month b').forEach((label,index)=>label.textContent=new Intl.DateTimeFormat(locale,{month:'short'}).format(new Date(2026,index,1)).replace(/\./g,'').toUpperCase());const legend=document.querySelector('.legend');legend.replaceChildren(...Object.entries(config.layers).map(([id,x])=>{const b=document.createElement('button');b.className='layer-toggle is-active';b.dataset.layer=id;b.setAttribute('aria-pressed','true');b.innerHTML=`<i class="dot" style="background:${x.color}"></i>${x.label}`;return b}));panel.querySelectorAll('.deadline-card').forEach(x=>x.remove());wheel.querySelectorAll('.event').forEach(x=>x.remove());config.items.forEach(item=>{const l=layer(item),color=config.layers[l].color,c=document.createElement('article'),e=document.createElement('button');c.className=`deadline-card is-${item.status}`;c.dataset.deadlineId=item.id;c.dataset.layer=l;c.innerHTML=`<span class="card-date"></span><div><p class="card-kind" style="color:${color}">${config.layers[l].label}</p><h2>${item.title}</h2><p class="rule-line"></p></div><button aria-label="More about ${item.title}">→</button>`;panel.querySelector('.all-deadlines').before(c);e.className='event';e.dataset.deadlineId=item.id;e.dataset.layer=l;e.dataset.label=item.title;e.style.backgroundColor=color;e.innerHTML='<span></span>';wheel.append(e)})}
function renderAnchorControls(){const editable=Object.entries(config.anchors).filter(([,anchor])=>anchor.configurable),target=document.querySelector('.anchor-controls');document.querySelector('#anchor-count').textContent=editable.length;target.replaceChildren(...editable.map(([id,anchor])=>{const label=document.createElement('label'),text=document.createElement('span'),fields=document.createElement('div'),field=document.createElement('input'),status=document.createElement('button');label.className='anchor-control';text.textContent=anchor.title;fields.className='anchor-fields';field.type='date';field.value=inputValue(new Date(year,anchor.defaultDate.month-1,anchor.defaultDate.day));field.dataset.anchorId=id;status.type='button';status.className='anchor-status is-tentative';status.dataset.anchorStatus=id;status.setAttribute('aria-pressed','false');status.textContent='Tentative';fields.append(field,status);label.append(text,fields);return label}))}
function resolve(){const runtimeAnchors=Object.fromEntries([...document.querySelectorAll('[data-anchor-id]')].map(field=>[field.dataset.anchorId,field.value]));const resolved=scheduleResolver(config,year,runtimeAnchors);return Object.fromEntries(config.items.map(item=>[item.id,{...resolved[item.id],rule:item.rule||(item.schedule.kind==='course'?`${item.schedule.count} course days · ${fmt(resolved[item.id].sessions[0])}–${fmt(resolved[item.id].sessions.at(-1))}`:'')}]))}
function paint(){const dates=resolve();config.items.forEach(item=>{const r=dates[item.id],c=document.querySelector(`.deadline-card[data-deadline-id="${item.id}"]`),e=document.querySelector(`.event[data-deadline-id="${item.id}"]`);c.querySelector('.card-date').textContent=fmt(r.date);c.querySelector('.rule-line').textContent=r.rule;const a=(r.date-new Date(year,0,1))/(new Date(year+1,0,1)-new Date(year,0,1))*Math.PI*2-Math.PI/2;e.style.setProperty('--x',`${50+Math.cos(a)*37}%`);e.style.setProperty('--y',`${50+Math.sin(a)*37}%`);e.querySelector('span').textContent=r.date.getDate();e.setAttribute('aria-label',`${fmt(r.date)}: ${item.title}`)});updateStatusStyles()}
function updateStatusStyles(){const statuses=statusResolver(config,Object.fromEntries(Object.entries(config.anchors).map(([id,anchor])=>[id,anchor.status||'tentative'])));config.items.forEach(item=>{const card=document.querySelector(`.deadline-card[data-deadline-id="${item.id}"]`),status=statuses[item.id];card.classList.remove('is-anchor','is-set','is-derived','is-derived-set');if(item.schedule.kind==='anchor')card.classList.add(status==='set'?'is-set':'is-anchor');else if(item.status==='set')card.classList.add('is-set');else card.classList.add(status==='set'?'is-derived-set':'is-derived')})}
const apply=()=>{wheel.style.setProperty('--wheel-rotation',`${rotation}deg`);wheel.style.setProperty('--today-label-rotation',`${-(rotation+todayAngle)}deg`)};function setYear(y){year=y;document.querySelectorAll('[data-anchor-id]').forEach(field=>{const d=date(field.value);field.value=inputValue(new Date(y,d.getMonth(),d.getDate()));config.anchors[field.dataset.anchorId].date=field.value});yearLabel.textContent=y;document.querySelectorAll('.year-text').forEach(x=>x.textContent=y);paint();const now=new Date(),focus=new Date(y,now.getMonth(),now.getDate()),p=(focus-new Date(y,0,1))/(new Date(y+1,0,1)-new Date(y,0,1));todayAngle=-180+p*360;rotation=-p*360;wheel.style.setProperty('--today-angle',`${todayAngle}deg`);wheel.querySelector('.today-line span').textContent=focus.getDate();apply()}
const setZoom=z=>{zoom=Math.max(.78,Math.min(1.5,z));wheel.style.setProperty('--wheel-scale',zoom);stage.classList.toggle('is-detailed',zoom>1.08);zoomLabel.textContent=`${Math.round(zoom*100)} %`};
render();renderAnchorControls();input=document.querySelector('[data-anchor-id="general_assembly"]');setYear(year);setZoom(zoom);document.querySelectorAll('[data-anchor-id]').forEach(field=>field.addEventListener('input',()=>{config.anchors[field.dataset.anchorId].date=field.value;paint()}));document.querySelectorAll('[data-anchor-status]').forEach(field=>field.addEventListener('click',()=>{const set=field.getAttribute('aria-pressed')!=='true';field.setAttribute('aria-pressed',String(set));field.classList.toggle('is-set',set);field.classList.toggle('is-tentative',!set);field.textContent=set?'Set':'Tentative';config.anchors[field.dataset.anchorStatus].status=set?'set':'tentative';updateStatusStyles()}));document.querySelector('#previous-year').onclick=()=>setYear(year-1);document.querySelector('#next-year').onclick=()=>setYear(year+1);document.querySelector('#today-button').onclick=()=>setYear(new Date().getFullYear());document.querySelector('#zoom-in').onclick=()=>setZoom(presets.find(x=>x>zoom+.005)??presets.at(-1));document.querySelector('#zoom-out').onclick=()=>setZoom(presets.filter(x=>x<zoom-.005).at(-1)??presets[0]);wheel.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom-e.deltaY*.0015)},{passive:false});
let dragA,dragR;const pointer=e=>{const b=wheel.getBoundingClientRect();return Math.atan2(e.clientY-b.top-b.height/2,e.clientX-b.left-b.width/2)*180/Math.PI};wheel.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;dragA=pointer(e);dragR=rotation;wheel.classList.add('is-dragging');wheel.setPointerCapture(e.pointerId)});wheel.addEventListener('pointermove',e=>{if(!wheel.hasPointerCapture(e.pointerId))return;rotation=dragR+pointer(e)-dragA;apply()});wheel.addEventListener('pointerup',e=>{wheel.releasePointerCapture(e.pointerId);wheel.classList.remove('is-dragging')});
document.querySelectorAll('.layer-toggle').forEach(b=>b.onclick=()=>{const on=!b.classList.contains('is-active');b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',on);document.querySelectorAll(`[data-layer="${b.dataset.layer}"]`).forEach(x=>x.classList.toggle('is-layer-hidden',!on))});document.querySelectorAll('.event').forEach(e=>e.onclick=()=>{document.querySelectorAll('.deadline-card').forEach(c=>c.classList.remove('active'));document.querySelector(`.deadline-card[data-deadline-id="${e.dataset.deadlineId}"]`)?.classList.add('active')});
